import React from 'react';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Sora, Raleway } from 'next/font/google';
import './globals.css';
import Header from '../components/Header';
import { Sidebar } from '../components/sidebar';
import Accounting from './Accounting/page';

const inter = Inter({ subsets: ['latin'] });
const raleway = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Service-center',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex ">
          <Sidebar />
          <div className='flex grow flex-wrap flex-col'>
            <Header />
            {children}
          </div>
        </div>

      </body>
    </html>
  );
}
